#!/bin/bash

# Symlink me to .git/hooks/pre-commit

skiplinter=$(git config --bool hooks.skiplinter)

if [[ "$skiplinter" == "true" ]]; then
    echo "Skipping linter pre-commit hook"
    exit 0
fi

# Run against the actual thing we're committing, not what's in the directory ATM
# (No idea how safe this is)
git stash -k -u 2>&1 > /dev/null
cmd='black --check *.py'
echo "Running check: $cmd"
eval $cmd
result=$?
# Restore state
git stash pop 2>&1 > /dev/null

if [[ $result -eq 0 ]]; then
    echo "Linter OK"
    exit 0
else
    cat <<EOF
Error: Linter complained.

If you want to ignore the linter's advice you can disable this check permanently using:
    git config hooks.skiplinter true
or only once using
    git -c "hooks.skiplinter=true" [whatever you had here]
EOF
    exit 1
fi
